language: node_js

node_js:
  - "0.12"

before_script:
  - pip install https://github.com/mkdocs/mkdocs/archive/master.zip --user
  - mkdocs build
  - npm install

script:
  - node publish-gh-pages.js
