language: node_js

node_js:
  - "0.12"

before_script:
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "travis-ci"
  - sudo pip install mkdocs
  - mkdocs build
  - npm install

script:
  - node publish-gh-pages.js
