site_name: hook-userguide
repo_url: https://github.com/doubleleft/hook-userguide/

site_description: |
    A RESTful and extendable Backend as a Service that provides
    instant backend to develop sites and apps faster, with dead-simple
    integration for JavaScript, iOS, Android and more.

pages:
  - ['index.md']

  # Getting started
  - ['Getting-started/How-to-use.md', 'Getting started', 'How to use']

  # Features
  - ['The-Basics/Application.md', 'Features', 'Application']
  - ['The-Basics/Authentication.md', 'Features', 'Authentication']
  - ['The-Basics/Collections.md', 'Features', 'Collections']
  - ['The-Basics/Schema.md', 'Features', 'Schema']
  - ['The-Basics/Custom-routes.md', 'Features', 'Custom routes']
  - ['The-Basics/Mail.md', 'Features', 'Mail']
  - ['The-Basics/Templates.md', 'Features', 'Templates']
  - ['The-Basics/Configuration.md', 'Features', 'Configuration']
  - ['The-Basics/Logging.md', 'Features', 'Logging']

  # More
  - ['More/Deployment.md', 'More', 'Deployment']

  # Tutorials
  - ['Tutorials/Score-ranking.md', 'Tutorials', 'Score ranking']

# google_analytics: ['UA-36723568-3', 'mkdocs.org']
use_directory_urls: true
theme: readthedocs
