site_name: hook-userguide
repo_url: https://github.com/doubleleft/hook-userguide/

site_description: |
    A RESTful and extendable Backend as a Service that provides
    instant backend to develop sites and apps faster, with dead-simple
    integration for JavaScript, iOS, Android and more.

pages:
  - ['index.md']

  # Getting started
  - ['Getting-started/How-to-use.md', 'Getting started', 'How to use']
  # - ['Getting-started/The-Commandline-Interface.md', 'Getting started', 'How to use']

  # Features
  - ['The-Basics/Application.md']
  - ['The-Basics/Collections.md']
  - ['The-Basics/Schema.md']
  - ['The-Basics/Custom-routes.md']
  - ['The-Basics/Configuration.md']
  - ['The-Basics/Template-engine.md']

  # More
  - ['More/Deployment.md']

  # Tutorials
  - ['Tutorials/OAuth-integration.md']
  - ['Tutorials/Score-ranking.md']
  - ['Tutorials/Sending-mails.md']

use_directory_urls: true
theme: readthedocs
